### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by arnaudon** [barahona-research-group/PyGenStability#22]
On some windows, it seems pthreads.h is missing, we'll investigate more on that.

**Comment by ZufeCy** [comment]
Hi, do you guys have a new solution for this problem. I've been stuck for almost a month

**Comment by arnaudon** [comment]
see comment in #50

**Comment by ZufeCy** [comment]
okay！ thank you bro.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "barahona-research-group/PyGenStability"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月15日(星期天) 晚上7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [barahona-research-group/PyGenStability] Windows compatibility (#22)





 
see comment in #50
