### ISSUE TITLE
Adding the feature to bigger libraries

### ISSUE THREAD

**Issue by BrandonKMLee** [barahona-research-group/PyGenStability#35]
There are other big libraries that could include RMST-RBS:
- Community Detection https://github.com/GiulioRossetti/cdlib
  - https://github.com/igraph/igraph and https://github.com/igraph/python-igraph
  - https://github.com/networkx/networkx
- Node/Graph Embedding https://github.com/benedekrozemberczki/karateclub
- Node/Graph Embedding https://github.com/shenweichen/GraphEmbedding

**Comment by arnaudon** [comment]
Hello! Can you say more about this issue? RMST is sparsifiction algorith, and RBS is for roles of nodes in directed graphs (we have some private repos for these, very rough, if you are interested). I don't think the codes you linked contain any of these 2, but if they do this is cool! This code is about Markov Stability, not RBS/RMST at all.

**Comment by BrandonKMLee** [comment]
@arnaudon apologies for my wording.
I do believe that the concept of Markov Stability could be included into other bigger Network research libraries, as it is really useful at "role discovery" (one of the most popular forms, the other being RoleSim)-related algorithms.

**Comment by arnaudon** [comment]
Sure! I'm not maintainer of these, so I can't do much!

**Comment by BrandonKMLee** [comment]
@mauriciobarahona BTW I kinda want to use this as an alternative to E-Mailing...
I would like to take a look at the source code for:
- https://arxiv.org/abs/1508.03165
- https://arxiv.org/abs/1311.6785
(for research purposes)

**Comment by arnaudon** [comment]
We'll try to make RMST/RBS open source soon, if this is what you want? If you email Mauricio, he can send you some matlab code of them I believe.

**Comment by BrandonKMLee** [comment]
Yeah, the Email does not seem to return anything, I assumed he is too busy with inboxes. Thanks for noting tho. #PythonGang
