### ISSUE TITLE
integrate leiden algorithm

### ISSUE THREAD

**Issue by arnaudon** [barahona-research-group/PyGenStability#36]

**Comment by michaelschaub** [comment]
https://github.com/vtraag/leidenalg is the official implementation ...

**Comment by arnaudon** [comment]
Yes, we know! This issue title is wrong, we're trying to interface the official implementation with this code, so one can use louvain or leiden the same way. It's work in progress here: https://github.com/barahona-research-group/PyGenStability/pull/43 and here: https://github.com/arnaudon/leidenalg/pull/1

**Comment by d-schindler** [comment]
I guess we can close this issue as Leiden has been integrated successfully with PR #43
