### ISSUE TITLE
installing bug

### ISSUE THREAD

**Issue by ZufeCy** [barahona-research-group/PyGenStability#50]
in the process of install pygenstability, i have the following problems：
can you help me to solve it?
building 'pygenstability.generalized_louvain' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iextra -ID:\Install_software\Anaconda\envs\tensorflow\lib\site-packages\pybind11\include -ID:\Install_software\Anaconda\envs\tensorflow\include -ID:\Install_software\Anaconda\envs\tensorflow\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tppygenstability/generalized_louvain/generalized_louvain.cpp /Fobuild\temp.win-amd64-3.7\Release\pygenstability/generalized_louvain/generalized_louvain.obj /EHsc /bigobj -std=c++11
cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
generalized_louvain.cpp
extra\lemon/bits/lock.h(24): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by arnaudon** [comment]
Ah sorry, we didn't not look at it ( I don't use windows personally).  Could you try to follow that? https://docs.microsoft.com/en-us/answers/questions/76739/fatal-error-c1083-cannot-open-include-file-39pthre.html  to see if it works? 
Thanks!

**Comment by arnaudon** [comment]
Hello, could you install the package in the end?
