### ISSUE TITLE
scale selection at margins of domain

### ISSUE THREAD

**Issue by d-schindler** [barahona-research-group/PyGenStability#62]
The current scale selection criterion is not reliable at the margins of the domain of Markov scale t due to:

1. Cut-off through windowing
2. The diagonal count of low values in the NVI(t,t') necessarily leads to smaller values at the margins because the diagonal is smaller. Hence, 1-NVI(t,.) tends to produce anomalous local minima at the margins.

While 1) is perhaps acceptable, Mauricio and me discussed that we should come up with a solution for 2). I will think about this and try a couple of things.

**Comment by arnaudon** [comment]
Can you somehow normalize by diagonal size?

**Comment by arnaudon** [comment]
Or just don't compute it at the margin, and write in docsctring why it is not reliable, so we don't compute it. User can increase markov time min/max to have larger range of scale detection.

**Comment by d-schindler** [comment]
I developed a new algorithm with @mauriciobarahona that seems to have much more robust. The idea is to pool the NVI(t,t') matrix and look at the local minima of its diagonal to identify the block structures. I will create a new branch for my implementation. This new scale selection algorithm will need a slightly modified summary plot, I will try to adapt.

**Comment by arnaudon** [comment]
Excellent!
